#include "preselection_plots.C"
void metStudy(TString bgdInputFile = "/data/smurf/data/Run2012_Summer12_SmurfV9_51X/mitf-alljets_noweights/metStudy_wwdy.root"){
  preselection_plots(0, 7,0,bgdInputFile);
  preselection_plots(0, 8,0,bgdInputFile);
  preselection_plots(0, 9,0,bgdInputFile);
  preselection_plots(0,10,0,bgdInputFile);
  preselection_plots(0,11,0,bgdInputFile);
  preselection_plots(0,12,0,bgdInputFile);
  preselection_plots(0,13,0,bgdInputFile);
  preselection_plots(0,14,0,bgdInputFile);
  preselection_plots(0,15,0,bgdInputFile);
  preselection_plots(0,16,0,bgdInputFile);
  preselection_plots(0,17,0,bgdInputFile);
  preselection_plots(0,18,0,bgdInputFile);
  preselection_plots(0,19,0,bgdInputFile);
  preselection_plots(0,20,0,bgdInputFile);
  preselection_plots(0,21,0,bgdInputFile);
  preselection_plots(0,22,0,bgdInputFile);
  preselection_plots(0, 7,1,bgdInputFile);
  preselection_plots(0, 8,1,bgdInputFile);
  preselection_plots(0, 9,1,bgdInputFile);
  preselection_plots(0,10,1,bgdInputFile);
  preselection_plots(0,11,1,bgdInputFile);
  preselection_plots(0,12,1,bgdInputFile);
  preselection_plots(0,13,1,bgdInputFile);
  preselection_plots(0,14,1,bgdInputFile);
  preselection_plots(0,15,1,bgdInputFile);
  preselection_plots(0,16,1,bgdInputFile);
  preselection_plots(0,17,1,bgdInputFile);
  preselection_plots(0,18,1,bgdInputFile);
  preselection_plots(0,19,1,bgdInputFile);
  preselection_plots(0,20,1,bgdInputFile);
  preselection_plots(0,21,1,bgdInputFile);
  preselection_plots(0,22,1,bgdInputFile);
  preselection_plots(0, 7,2,bgdInputFile);
  preselection_plots(0, 8,2,bgdInputFile);
  preselection_plots(0, 9,2,bgdInputFile);
  preselection_plots(0,10,2,bgdInputFile);
  preselection_plots(0,11,2,bgdInputFile);
  preselection_plots(0,12,2,bgdInputFile);
  preselection_plots(0,13,2,bgdInputFile);
  preselection_plots(0,14,2,bgdInputFile);
  preselection_plots(0,15,2,bgdInputFile);
  preselection_plots(0,16,2,bgdInputFile);
  preselection_plots(0,17,2,bgdInputFile);
  preselection_plots(0,18,2,bgdInputFile);
  preselection_plots(0,19,2,bgdInputFile);
  preselection_plots(0,20,2,bgdInputFile);
  preselection_plots(0,21,2,bgdInputFile);
  preselection_plots(0,22,2,bgdInputFile);
}
